### ISSUE TITLE
Error starting sample map

### ISSUE THREAD

**Issue by micheal-w-wells** [hermanho/react-leaflet-pouchdb-tilelayer#4]
steps to reproduce:

1. clone
2. npm install
3. npm start

Error:

Failed to compile.

./src/lib/pouchdb-tilelayer.ts
Module not found: Can't resolve './worker.embedded' in '/Users/<my username and dir/react-leaflet-pouchdb-tilelayer/src/lib'

node -v: v12.3.1
npm -v: 6.9.0

**Comment by hermanho** [comment]
please execute "npm run build:worker" before start
